/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//İREM FOÇALI 18070006032
package homework_bmr;

/**
 *
 * @author ASUS
 */
public class homework_bmr extends javax.swing.JFrame {

    /**
     * Creates new form homework_bmr
     */
    public homework_bmr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        calculate_BMR = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        age_enter = new javax.swing.JTextField();
        choose_your_gender = new javax.swing.JLabel();
        male_radiobtn = new javax.swing.JRadioButton();
        female_radiobtn = new javax.swing.JRadioButton();
        weight_label = new javax.swing.JLabel();
        height_label = new javax.swing.JLabel();
        height_slider = new javax.swing.JSlider();
        select_result_label = new javax.swing.JLabel();
        kilocalories_button = new javax.swing.JRadioButton();
        kilojoules_button = new javax.swing.JRadioButton();
        selectbasalmetabolicrate_label = new javax.swing.JLabel();
        m_st_jeor_formula_button = new javax.swing.JRadioButton();
        rev_harris_benedict_button = new javax.swing.JRadioButton();
        yourbmr_label = new javax.swing.JLabel();
        result_bmr_textfield = new javax.swing.JTextField();
        weight_slider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        errorlabel = new javax.swing.JLabel();
        calculatebutton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        calculate_BMR.setBackground(new java.awt.Color(255, 255, 204));
        calculate_BMR.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        calculate_BMR.setForeground(new java.awt.Color(204, 0, 51));
        calculate_BMR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculate_BMR.setText("CALCULATE YOUR BMR ");
        calculate_BMR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 153), new java.awt.Color(255, 255, 153), new java.awt.Color(255, 255, 153), new java.awt.Color(255, 255, 153)));

        age_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        age_label.setForeground(new java.awt.Color(0, 0, 153));
        age_label.setText("Age :");

        age_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_enterActionPerformed(evt);
            }
        });

        choose_your_gender.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        choose_your_gender.setForeground(new java.awt.Color(0, 0, 153));
        choose_your_gender.setText("Choose Your Gender :");

        male_radiobtn.setText("male");

        female_radiobtn.setText("female");
        female_radiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radiobtnActionPerformed(evt);
            }
        });

        weight_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        weight_label.setForeground(new java.awt.Color(0, 0, 153));
        weight_label.setText("Your weight :");

        height_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        height_label.setForeground(new java.awt.Color(0, 0, 153));
        height_label.setText("Your height :");

        height_slider.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        height_slider.setMajorTickSpacing(10);
        height_slider.setMaximum(200);
        height_slider.setPaintLabels(true);
        height_slider.setPaintTicks(true);
        height_slider.setValue(0);
        height_slider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        height_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                height_sliderStateChanged(evt);
            }
        });

        select_result_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        select_result_label.setForeground(new java.awt.Color(0, 0, 153));
        select_result_label.setText("Select Unit Of Result :");

        kilocalories_button.setText("kilocalories");

        kilojoules_button.setText("kilojoules");

        selectbasalmetabolicrate_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        selectbasalmetabolicrate_label.setForeground(new java.awt.Color(0, 0, 153));
        selectbasalmetabolicrate_label.setText("Select Formula To Be Used For Estimation Of Basal Metabolic Rate : ");

        m_st_jeor_formula_button.setText("Mifflin-St Jeor Formula");

        rev_harris_benedict_button.setText("Revised Harris-Benedict Formula");

        yourbmr_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yourbmr_label.setForeground(new java.awt.Color(255, 102, 51));
        yourbmr_label.setText("YOUR BMR :");

        result_bmr_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_bmr_textfieldActionPerformed(evt);
            }
        });

        weight_slider.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        weight_slider.setMajorTickSpacing(10);
        weight_slider.setMaximum(200);
        weight_slider.setPaintLabels(true);
        weight_slider.setPaintTicks(true);
        weight_slider.setValue(0);
        weight_slider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        weight_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                weight_sliderStateChanged(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        errorlabel.setBackground(new java.awt.Color(255, 255, 153));
        errorlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(0, 102, 102));
        errorlabel.setText("(Age range: 15-80)");
        errorlabel.setToolTipText("");

        calculatebutton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        calculatebutton.setForeground(new java.awt.Color(0, 102, 102));
        calculatebutton.setText("CALCULATE");
        calculatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rev_harris_benedict_button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(select_result_label, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(kilocalories_button)
                            .addGap(59, 59, 59)
                            .addComponent(kilojoules_button))
                        .addComponent(selectbasalmetabolicrate_label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculate_BMR, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 209, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(age_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(choose_your_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(male_radiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(female_radiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(weight_slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                        .addComponent(height_slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(102, 102, 102)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(m_st_jeor_formula_button)
                                    .addGap(385, 385, 385))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(yourbmr_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(result_bmr_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(calculatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(190, 190, 190))))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(height_label, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(calculate_BMR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose_your_gender)
                    .addComponent(male_radiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(female_radiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(weight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weight_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(height_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(height_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(select_result_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kilocalories_button)
                            .addComponent(kilojoules_button))
                        .addGap(30, 30, 30)
                        .addComponent(selectbasalmetabolicrate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rev_harris_benedict_button)
                            .addComponent(m_st_jeor_formula_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(yourbmr_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(result_bmr_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void female_radiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_radiobtnActionPerformed

    private void weight_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_weight_sliderStateChanged
      
        jLabel1.setText(Integer.toString(weight_slider.getValue())); 
    }//GEN-LAST:event_weight_sliderStateChanged

    private void height_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_height_sliderStateChanged
        jLabel2.setText(Integer.toString(height_slider.getValue()));
    }//GEN-LAST:event_height_sliderStateChanged

    private void age_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_enterActionPerformed
        int age = Integer.parseInt(age_enter.getText());
        if(age>=15 && age<=80){
            age_enter.setText(String.valueOf(age));
        }
        else{
            errorlabel.setText("Please enter the age value between 15-80");
        }
    }//GEN-LAST:event_age_enterActionPerformed

    private void calculatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebuttonActionPerformed
        int weight;
        int height;
        int age;
        double result_bmr ;
        double result_bmr_kilojoules;
        weight = Integer.parseInt(jLabel1.getText());
        height = Integer.parseInt(jLabel2.getText());
        age = Integer.parseInt(age_enter.getText());
        if(age>=15 && age<=80){
            errorlabel.setText(" ");
            if(female_radiobtn.isSelected()&& m_st_jeor_formula_button.isSelected()){
            //BMR = 10W + 6.25H - 5A - 161
            result_bmr = (10*weight + 6.25*height -5*age -161)*(0.001) ;
            
            if(kilocalories_button.isSelected()){
                result_bmr_textfield.setText(String.valueOf(result_bmr));
            }
            else{
                //1 kcal = 4.1868 kJ(kilojoules)
                result_bmr_kilojoules = result_bmr*4.1868;
                result_bmr_textfield.setText(String.valueOf(result_bmr_kilojoules));
            }
        }
        else if(female_radiobtn.isSelected()&& rev_harris_benedict_button.isSelected()){
             //BMR = 9.247W + 3.098H - 4.330A + 447.593
             result_bmr = (9.247*weight + 3.098*height - 4.330*age + 447.593) *(0.001);
             if(kilocalories_button.isSelected()){
                result_bmr_textfield.setText(String.valueOf(result_bmr));
            }
            else{
                //1 kcal = 4.1868 kJ(kilojoules)
                result_bmr_kilojoules = result_bmr*4.1868;
                result_bmr_textfield.setText(String.valueOf(result_bmr_kilojoules));
                
            }
        }
        else if(male_radiobtn.isSelected()&& m_st_jeor_formula_button.isSelected()){
            // BMR = 10W + 6.25H - 5A + 5
            result_bmr = (10*weight + 6.25*height -5*age +5)*(0.001);
            if(kilocalories_button.isSelected()){
                result_bmr_textfield.setText(String.valueOf(result_bmr));
            }
            else{
                result_bmr_kilojoules = result_bmr*4.1868;
                result_bmr_textfield.setText(String.valueOf(result_bmr_kilojoules));
            }
        }
         else if(male_radiobtn.isSelected()&& rev_harris_benedict_button.isSelected()){
             //BMR = 13.397W + 4.799H - 5.677A + 88.362
             result_bmr = (13.397*weight + 4.799*height - 5.677*age + 88.362)*(0.001) ;
             if(kilocalories_button.isSelected()){
                result_bmr_textfield.setText(String.valueOf(result_bmr));
            }
            else{
                result_bmr_kilojoules = result_bmr*4.1868;
                result_bmr_textfield.setText(String.valueOf(result_bmr_kilojoules));
            }
        }    
    }
    else{
             errorlabel.setText("Please enter the age value between 15-80");
             
       
     }   
    }//GEN-LAST:event_calculatebuttonActionPerformed

    private void result_bmr_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_bmr_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_bmr_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homework_bmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homework_bmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homework_bmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homework_bmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homework_bmr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_enter;
    private javax.swing.JLabel age_label;
    private javax.swing.JLabel calculate_BMR;
    private javax.swing.JButton calculatebutton;
    private javax.swing.JLabel choose_your_gender;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JRadioButton female_radiobtn;
    private javax.swing.JLabel height_label;
    private javax.swing.JSlider height_slider;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton kilocalories_button;
    private javax.swing.JRadioButton kilojoules_button;
    private javax.swing.JRadioButton m_st_jeor_formula_button;
    private javax.swing.JRadioButton male_radiobtn;
    private javax.swing.JTextField result_bmr_textfield;
    private javax.swing.JRadioButton rev_harris_benedict_button;
    private javax.swing.JLabel select_result_label;
    private javax.swing.JLabel selectbasalmetabolicrate_label;
    private javax.swing.JLabel weight_label;
    private javax.swing.JSlider weight_slider;
    private javax.swing.JLabel yourbmr_label;
    // End of variables declaration//GEN-END:variables
}
